name: CD

on: 
  workflow_dispatch:
    inputs:
      charts:
        description: 'Charts separated by spaces'
        required: true
        default: 'dummy'
      images:
        description: 'Images separated by spaces'
        required: true
        default: 'neateas/onsitev2-document-store'
      environment:
        description: 'Environment'
        required: true
        default: 'prod'
  push:
    tags: [ 'v*' ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_REPO_API_TOKEN: ${{ secrets.GIT_REPO_API_TOKEN }}

jobs:
  build:
    steps:
      - uses: OWNER/hello-world-composite-action@SHA
        with:
          charts: ${{ github.event.inputs.charts }}
          images: ${{ github.event.inputs.images }}
          environment: ${{ github.event.inputs.environment }}
          sections: "service"
