name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  verify:
    uses: neate-org/neate-github-actions/.github/workflows/ci_template.yml@master
    with:
      commands: "-build -test"
      sections: "service"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}