name: CI Template

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      PRIVATE_REPO_TOKEN:
        required: true
    inputs:
      sections:
        type: string
        description: "Dbm sections separated by spaces"
        required: false
        default: "service"
      python_version:
        type: string
        description: "Python version to use"
        required: false
        default: "3.9"
      docker_registry:
        type: string
        description: "Docker registry to use"
        required: false
        default: "docker.io"
  workflow_dispatch:
    inputs:
      sections:
        description: "Dbm sections separated by spaces"
        required: false
        default: "service"
      python_version:
        description: "Python version to use"
        required: false
        default: "3.9"
      docker_registry:
        description: "Docker registry to use"
        required: false
        default: "docker.io"

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      - name: setup Docker
        uses: docker/setup-docker-action@v4

      - name: login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Set image tag
        shell: bash
        run: |
          if [[ "$CI_ACTION_REF_NAME_SLUG" == "master" || "$CI_ACTION_REF_NAME_SLUG" == "main" ]] ; then 
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "IMAGE_TAG=$CI_ACTION_REF_NAME_SLUG" >> $GITHUB_ENV
          fi

      - name: Install requirements
        shell: bash
        run: |
          pip install DockerBuildManagement

      - name: Verify
        shell: bash
        run: |
          dbm -build -test ${{ inputs.sections }}
